sudo: required
services:
  - docker

before_install:
  - docker build -t youssefmostafa2510/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true youssefmostafa2510/react-test npm test

after_success:
  - docker build -t youssefmostafa2510/multi-client ./client
  - docker build -t youssefmostafa2510/multi-nginx ./nginx
  - docker build -t youssefmostafa2510/multi-server ./server
  - docker build -t youssefmostafa2510/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push youssefmostafa2510/multi-client
  - docker push yousseefmostafa2510/multi-nginx
  - docker push youssefmostafa2510/multi-server
  - docker push youssefmostafa2510/multi-worker
  # Add env vars in travis ci
